pipeline:
  name: CI Pipeline 1
  identifier: CI_Pipeline_1
  projectIdentifier: Interview_Project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: SC_Git
        repoName: gosample
        build: <+input>
  stages:
    - stage:
        name: Build Stage
        identifier: Build_Stage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.DockerHubConnector
                    repo: stevecoccia/myapp:tagname
                    tags:
                      - test_v1
                    context: .
                    buildArgs:
                      GITHUB_TOKEN: ${secrets.getValue("GitHubToken")}
                    envVariables:
                      GITHUB_TOKEN: GithubToken
